@startuml Diagramme_Interaction-getMessageTopic

skinparam backgroundColor #EEEEEE

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor white
ParticipantBackgroundColor DodgerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor white
}

participant Client
activate Client
Client -> MOMService: getMessagePeerToPeer (HTTP)
activate MOMService

MOMService -> MOMDAO: getMessageFromApplication
activate MOMDAO

MOMDAO -> MOMDAO: getApplicationReceiver
MOMDAO -> MOMDAO: getApplicationSender


MOMDAO -> Application: getMessageForApplication
activate Application

Application -> MessageQueue: getMessageToReader
activate MessageQueue

MessageQueue -> Message: erasable
Message --> MessageQueue

MessageQueue --> Application: List Message
deactivate MessageQueue
Application --> MOMDAO: List Message
deactivate Application
MOMDAO --> MOMService: List Message
deactivate MOMDAO
MOMService --> Client: List Message
deactivate MOMService
deactivate Client


@enduml

'alt successful case
'else something
'end